<TestingScreen>:
    name: 'testing'
    MDScreen:
        md_bg_color: 28/255, 140/255, 140/255, 1

        FloatLayout:
            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                padding: [dp(20), dp(40), dp(20), dp(30)]
                spacing: dp(50)
                pos_hint: {"top": 1}

                MDCard:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: dp(90)
                    md_bg_color: 173/255, 216/255, 230/255, 1  # Цвет фона карточки
                    radius: [15, 15, 15, 15]
                    pos_hint: {"top": 0.95}

                    MDLabel:
                        text: "Тестування"
                        font_name: "juneg"
                        halign: "center"
                        theme_text_color: "Primary"
                        font_size: sp(24)

                MDCard:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    md_bg_color: 255/255, 223/255, 186/255, 1  # Цвет фона карточки
                    radius: [15, 15, 15, 15]
                    padding: dp(10)

                    MDLabel:
                        text: "Пройдіть тестування, яке допоможе визначити ваш поточний рівень володіння англійською мовою. Тест включає завдання різної складності, і на його проходження знадобиться 15-20 хвилин. "
                        font_name: "Clearsan"
                        halign: "justify"
                        theme_text_color: "Primary"
                        font_size: sp(14)
                        size_hint_y: None
                        height: self.texture_size[1]

            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                padding: [dp(20), dp(30), dp(20), dp(30)]
                spacing: dp(50)
                pos_hint: {"center_x": 0.5, "center_y": 0.2}

                MDCard:
                    orientation: 'vertical'
                    size_hint_x: 0.6
                    size_hint_y: None
                    elevation: 1
                    height: self.minimum_height
                    md_bg_color: 255/255, 225/255, 158/255, 1  # Цвет фона карточки
                    padding: [10, 40, 10, 40]
                    radius: [15, 15, 15, 15]
                    pos_hint: {"center_x": 0.5}
                    on_press: app.root.current = 'testing_questions'

                    MDLabel:
                        text: "Розпочати тест"
                        font_name: "juneg"
                        halign: "center"
                        theme_text_color: "Primary"
                        font_size: sp(20)


            MDIconButton:
                icon: 'arrow-left'
                pos_hint: {"x": 0, "top": 1}  # Левый верхний угол
                size_hint: None, None
                size: dp(56), dp(56)  # Размер кнопки возврата
                on_release: app.change_screen_item('main')
